import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

import { DEFAULT_PROJECT_FONT_IDS, DENEB_FONT_REGISTRY } from './registry';
import {
  collectFontIdsFromSiteData,
  lookupFontDefinition,
  normalizeFontId,
  resolveInstallableFont,
} from './resolve';
import type { DenebFontDefinition, DenebFontManifest } from './types';

export const FONTS_MANIFEST_REL = '.deneb/fonts.json';
export const FONTS_CSS_REL = 'src/fonts/deneb-fonts.css';
export const FONTS_CSS_IMPORT = '../fonts/deneb-fonts.css';

const SKIP_HOST_NAMES = new Set([
  '@deneb-ui/ui',
  '@deneb-ui/core',
  '@deneb-ui/cli',
  '@deneb-ui/create-template',
  'deneb-ui-framework-monorepo',
]);

export interface InstallProjectFontsOptions {
  projectDir: string;
  fontIds?: string[];
  all?: boolean;
  quiet?: boolean;
}

export interface InstallProjectFontsResult {
  ok: boolean;
  skipped?: string;
  installed: string[];
  packages: string[];
  cssPath?: string;
  manifestPath?: string;
  layoutPatched?: boolean;
  warnings: string[];
}

function log(quiet: boolean | undefined, message: string) {
  if (!quiet) console.log(message);
}

function readJsonSafe(filePath: string): Record<string, unknown> | null {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8')) as Record<string, unknown>;
  } catch {
    return null;
  }
}

export function findSiteDataPath(projectDir: string): string | null {
  const candidates = [
    path.join(projectDir, 'src', 'data', 'site-data.json'),
    path.join(projectDir, 'site-data.json'),
    path.join(projectDir, 'data', 'site-data.json'),
  ];
  return candidates.find((candidate) => fs.existsSync(candidate)) ?? null;
}

export function findHostProject(startDir: string): string | null {
  let dir = path.resolve(startDir);
  for (let i = 0; i < 12; i++) {
    const pkgPath = path.join(dir, 'package.json');
    if (fs.existsSync(pkgPath)) {
      const pkg = readJsonSafe(pkgPath);
      const name = typeof pkg?.name === 'string' ? pkg.name : '';
      if (!SKIP_HOST_NAMES.has(name)) {
        const deps = {
          ...((pkg?.dependencies as Record<string, string> | undefined) ?? {}),
          ...((pkg?.devDependencies as Record<string, string> | undefined) ?? {}),
        };
        if (deps['@deneb-ui/ui'] || deps.next || deps.react) {
          return dir;
        }
      }
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

function detectPackageManager(projectDir: string): 'npm' | 'pnpm' | 'yarn' {
  if (fs.existsSync(path.join(projectDir, 'pnpm-lock.yaml'))) return 'pnpm';
  if (fs.existsSync(path.join(projectDir, 'yarn.lock'))) return 'yarn';
  return 'npm';
}

function buildFontsourceCssEntries(font: DenebFontDefinition): string[] {
  const pkg = font.fontsourcePackage;
  if (!pkg) return [];
  if (font.variable) {
    return [`@import '@fontsource/${pkg}/index.css';`];
  }
  const weights = font.weights.length > 0 ? font.weights : [400];
  const lines: string[] = [];
  for (const weight of weights) {
    lines.push(`@import '@fontsource/${pkg}/${weight}.css';`);
    if (font.italic) {
      lines.push(`@import '@fontsource/${pkg}/${weight}-italic.css';`);
    }
  }
  return lines;
}

export function generateFontsCss(fonts: DenebFontDefinition[]): string {
  const lines = [
    '/*',
    ' * DENEB Fonts — self-hosted via @fontsource',
    ' * Generated by: deneb fonts install / @deneb-ui/ui postinstall',
    ' */',
    '',
  ];
  for (const font of fonts) {
    lines.push(`/* ${font.label} (${font.id}) */`);
    lines.push(...buildFontsourceCssEntries(font));
    lines.push('');
  }
  lines.push(':root { --deneb-fonts-selfhosted: 1; }');
  lines.push('');
  return `${lines.join('\n').trim()}\n`;
}

function findLayoutPath(projectDir: string): string | undefined {
  const layoutCandidates = [
    path.join(projectDir, 'src', 'app', 'layout.tsx'),
    path.join(projectDir, 'src', 'app', 'layout.jsx'),
    path.join(projectDir, 'app', 'layout.tsx'),
    path.join(projectDir, 'app', 'layout.jsx'),
  ];
  return layoutCandidates.find((candidate) => fs.existsSync(candidate));
}

function ensureRootHydrationGuard(source: string): string {
  let next = source;
  if (!/<html\b[^>]*suppressHydrationWarning/.test(next)) {
    next = next.replace(/<html\b([^>]*)>/, '<html$1 suppressHydrationWarning>');
  }
  if (!/<body\b[^>]*suppressHydrationWarning/.test(next)) {
    next = next.replace(/<body\b([^>]*)>/, '<body$1 suppressHydrationWarning>');
  }
  return next;
}

function fontsCssImportSpecifier(projectDir: string, layoutPath: string): string {
  const cssAbs = path.join(projectDir, FONTS_CSS_REL);
  let rel = path.relative(path.dirname(layoutPath), cssAbs).replace(/\\/g, '/');
  if (!rel.startsWith('.')) rel = `./${rel}`;
  return rel;
}

export function stripNextFontGoogle(source: string): { source: string; stripped: boolean } {
  if (!source.includes("next/font/google")) {
    return { source, stripped: false };
  }

  let next = source;
  // Remove import { ... } from "next/font/google"
  next = next.replace(/import\s*\{[^}]*\}\s*from\s*['"]next\/font\/google['"];?\r?\n?/g, "");
  // Remove font const declarations with options like variable, subsets, display
  next = next.replace(/const\s+[a-zA-Z0-9_$]+\s*=\s*[a-zA-Z0-9_$]+\(\s*\{[\s\S]*?\}\s*\);?\r?\n?/g, (match) => {
    if (match.includes("variable:") || match.includes("subsets:") || match.includes("display:")) {
      return "";
    }
    return match;
  });
  // Clean up font variable classes e.g. ${fraunces.variable}
  next = next.replace(/\$\{[a-zA-Z0-9_$]+\.variable\}\s*/g, "");

  return { source: next, stripped: true };
}

function patchLayoutImport(projectDir: string): { patched: boolean; reason: string; layoutPath?: string } {
  const layoutPath = findLayoutPath(projectDir);
  if (!layoutPath) return { patched: false, reason: 'layout.tsx not found' };

  const specifier = fontsCssImportSpecifier(projectDir, layoutPath);
  const importLine = `import '${specifier}';`;
  let source = fs.readFileSync(layoutPath, 'utf8');
  const { source: ungoogled, stripped } = stripNextFontGoogle(source);
  source = ungoogled;

  // Older installer wrote ./fonts/... next to layout.tsx; the CSS lives in src/fonts.
  if (source.includes("import './fonts/deneb-fonts.css'")) {
    source = ensureRootHydrationGuard(source.replace("import './fonts/deneb-fonts.css';", importLine));
    fs.writeFileSync(layoutPath, source, 'utf8');
    return { patched: true, reason: 'rewrote stale import', layoutPath };
  }
  if (source.includes('import "./fonts/deneb-fonts.css"')) {
    source = ensureRootHydrationGuard(source.replace('import "./fonts/deneb-fonts.css";', importLine));
    fs.writeFileSync(layoutPath, source, 'utf8');
    return { patched: true, reason: 'rewrote stale import', layoutPath };
  }
  if (source.includes('deneb-fonts.css')) {
    const guarded = ensureRootHydrationGuard(source);
    if (guarded !== source || stripped) {
      fs.writeFileSync(layoutPath, guarded, 'utf8');
      return { patched: true, reason: 'hydration guard', layoutPath };
    }
    return { patched: false, reason: 'already imported', layoutPath };
  }

  if (source.includes("import './globals.css'")) {
    source = source.replace("import './globals.css';", `import './globals.css';\n${importLine}`);
  } else if (source.includes('import "./globals.css"')) {
    source = source.replace('import "./globals.css";', `import "./globals.css";\n${importLine}`);
  } else {
    source = `${importLine}\n${source}`;
  }
  source = ensureRootHydrationGuard(source);
  fs.writeFileSync(layoutPath, source, 'utf8');
  return { patched: true, reason: 'patched', layoutPath };
}

function resolveInstallableList(
  projectDir: string,
  options: InstallProjectFontsOptions,
): { fonts: DenebFontDefinition[]; warnings: string[] } {
  const warnings: string[] = [];
  const ids = new Set<string>();

  if (options.all) {
    for (const font of DENEB_FONT_REGISTRY) {
      if (font.fontsourcePackage) ids.add(font.id);
    }
  } else if (options.fontIds && options.fontIds.length > 0) {
    for (const id of options.fontIds) ids.add(normalizeFontId(id));
  } else {
    const siteDataPath = findSiteDataPath(projectDir);
    if (siteDataPath) {
      const siteData = readJsonSafe(siteDataPath) ?? {};
      for (const id of collectFontIdsFromSiteData(siteData)) ids.add(id);
    }
    if (ids.size === 0) {
      for (const id of DEFAULT_PROJECT_FONT_IDS) ids.add(id);
    }
  }

  const fonts: DenebFontDefinition[] = [];
  for (const id of ids) {
    const font = resolveInstallableFont(id) ?? lookupFontDefinition(id);
    if (!font?.fontsourcePackage) {
      warnings.push(`Skipped "${id}" — not available on Google Fonts / @fontsource`);
      continue;
    }
    if (!fonts.find((entry) => entry.id === font.id)) fonts.push(font);
  }
  return { fonts, warnings };
}

function packagesAlreadyPresent(projectDir: string, packages: string[]): boolean {
  const pkg = readJsonSafe(path.join(projectDir, 'package.json'));
  const deps = {
    ...((pkg?.dependencies as Record<string, string> | undefined) ?? {}),
    ...((pkg?.devDependencies as Record<string, string> | undefined) ?? {}),
  };
  return packages.every((name) => Boolean(deps[name]));
}

function installPackages(projectDir: string, packages: string[], quiet?: boolean): void {
  if (packages.length === 0) return;
  if (packagesAlreadyPresent(projectDir, packages)) return;

  const pm = detectPackageManager(projectDir);
  const args =
    pm === 'pnpm'
      ? ['add', ...packages]
      : pm === 'yarn'
        ? ['add', ...packages]
        : ['install', ...packages, '--save'];
  const res = spawnSync(pm, args, {
    cwd: projectDir,
    stdio: quiet ? 'pipe' : 'inherit',
    shell: true,
    env: { ...process.env, DENEB_SKIP_FONTS: '1' },
  });
  if (res.status !== 0) {
    throw new Error(`${pm} install failed for font packages`);
  }
}

export function installProjectFonts(
  options: InstallProjectFontsOptions,
): InstallProjectFontsResult {
  const projectDir = path.resolve(options.projectDir);
  const warnings: string[] = [];

  if (process.env.DENEB_SKIP_FONTS === '1') {
    return { ok: true, skipped: 'DENEB_SKIP_FONTS=1', installed: [], packages: [], warnings };
  }
  if (!fs.existsSync(projectDir)) {
    return { ok: false, skipped: 'directory not found', installed: [], packages: [], warnings };
  }

  const { fonts, warnings: resolveWarnings } = resolveInstallableList(projectDir, options);
  warnings.push(...resolveWarnings);
  if (fonts.length === 0) {
    return { ok: false, installed: [], packages: [], warnings };
  }

  const packages = fonts.map((font) => `@fontsource/${font.fontsourcePackage}`);
  log(options.quiet, `\nInstalling ${fonts.length} DENEB font package(s) into ${projectDir}\n`);
  installPackages(projectDir, packages, options.quiet);

  const cssPath = path.join(projectDir, FONTS_CSS_REL);
  fs.mkdirSync(path.dirname(cssPath), { recursive: true });
  fs.writeFileSync(cssPath, generateFontsCss(fonts), 'utf8');

  const manifestPath = path.join(projectDir, FONTS_MANIFEST_REL);
  const manifest: DenebFontManifest = {
    version: 1,
    installedAt: new Date().toISOString(),
    fonts: fonts.map((font) => ({
      id: font.id,
      fontsourcePackage: font.fontsourcePackage as string,
      weights: font.weights,
      variable: font.variable,
    })),
  };
  fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
  fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');

  const layout = patchLayoutImport(projectDir);
  if (!options.quiet) {
    for (const warning of warnings) console.warn(`⚠ ${warning}`);
    console.log(`✔ Wrote ${FONTS_CSS_REL}`);
    console.log(`✔ Wrote ${FONTS_MANIFEST_REL}`);
    if (layout.patched) {
      console.log(`✔ Patched layout font import`);
    } else {
      console.log(`ℹ Add to layout: import '${FONTS_CSS_IMPORT}'; (${layout.reason})`);
    }
  }

  return {
    ok: true,
    installed: fonts.map((font) => font.id),
    packages,
    cssPath,
    manifestPath,
    layoutPatched: layout.patched,
    warnings,
  };
}

export function installFontsForHostOf(packageDir: string): InstallProjectFontsResult {
  const host = findHostProject(packageDir);
  if (!host) {
    return {
      ok: true,
      skipped: 'no host Next/React app found',
      installed: [],
      packages: [],
      warnings: [],
    };
  }
  return installProjectFonts({ projectDir: host, quiet: true });
}
